Add support for mysql 8.0.30 and remove support for mysql 8.0.26 [1.7.0 Release]
pivotal-cf/docs-mysql-k8s pull request #120
Opened 2023-01-12 21:13 UTC by abubakarm94

As part of 1.7.0 Release, we're removing support for mysql 8.0.26 and adding support for mysql 8.0.30

2023-02-02 21:45 UTC, ssapra requested changes

2023-02-02 21:45 UTC, ssapra commented on property-reference-mysql.html.md.erb
> +mysql-8.0.29, and mysql-8.0.30 this value defaults to mysql-8.0.29.<br/>
The new default is mysql-8.0.30

2023-02-17 17:26 UTC, ssapra approved these changes

2023-02-17 17:51 UTC, dyozie approved these changes

2023-02-17 19:07 UTC, merged