Remove Tanzu from product name
pivotal-cf/docs-mysql-k8s pull request #121
Opened 2023-01-24 00:54 UTC by SMiller70

[#183586151](https://www.pivotaltracker.com/story/show/183586151)

Authored-by: Shelby Miller <mshelby@vmware.com>

2023-01-24 01:24 UTC, swati-nair commented on create-delete-mysql.html.md.erb
> +### <a id="version"></a> Selecting the VMware MySQL Operator Version
This section should be `VMware MySQL Version` since it's talking about MySQL version and not the operator.

Same comment applies to all the statements inside this section which say Operator Version

2023-01-24 01:24 UTC, swati-nair commented on create-delete-mysql.html.md.erb
> +title: Creating and Deleting VMware SQL with MySQL for Kubernetes Instances
You can avoid the longer name and keep it as before since it doesn't mention Tanzu.

2023-01-24 01:24 UTC, swati-nair commented on create-delete-mysql.html.md.erb
> +    To customize the VMware MySQL Operator instance version, use one of the values under the column `NAME` displayed at the output of the command `kubectl get mysqlversions`, and specify the `mysql.s
same here. No need of `Operator`

2023-01-24 01:24 UTC, swati-nair commented on create-delete-mysql.html.md.erb
> +    You may also customize your VMware MySQL Operator instance resources, instance storage class, storage size, high availability, node affinity and tolerations, PVC retention policy, service type (C
same here. No need of `Operator`

2023-01-24 01:24 UTC, swati-nair commented on create-delete-mysql.html.md.erb
> +## <a id='delete-instance'></a> Delete a VMware MySQL Operator Instance
same here. No need of `Operator`

2023-01-24 01:24 UTC, swati-nair commented on creating-service-bindings.html.md.erb
> +title: Connecting an Application to a VMware SQL with MySQL for Kubernetes Instance
same comment as before. can avoid long name, keeping it as before.

2023-01-24 01:24 UTC, swati-nair commented on creating-service-bindings.html.md.erb
> +The VMware MySQL Operator 1.3 supports Service Binding with Tanzu Application Platform (TAP). This feature eliminates the manual management of the configuration steps needed to securely and successfu
VMware MySQL Operator deployment -> VMware MySQL deployment

2023-01-24 01:24 UTC, swati-nair commented on creating-service-bindings.html.md.erb
> +## <a id="tas_apps"></a>Binding VMware MySQL Operator to a TAS Application
no need of `Operator`

2023-01-24 01:24 UTC, swati-nair commented on high-availability.html.md.erb
> +title: Configuring VMware SQL with MySQL for Kubernetes Instances for High Availability
same.. can keep it as is (unless someone has explicitly asked to change this title)

2023-01-24 01:24 UTC, swati-nair commented on index.html.md.erb
> +By default, VMware MySQL Operator instances are provisioned with secure and functional settings to meet application developer expectations for a general-use relational
no `Operator`

2023-01-24 01:24 UTC, swati-nair commented on install-operator.html.md.erb
>  	   registry.tanzu.vmware.com/tanzu-mysql-for-kubernetes/tanzu-mysql-operator   	       1.6.2     8b46a4d26aa0   2 weeks ago    76.9MB
are we going to change the registry and image names? 
If we are, we can address this later in docs as a part#2 refactor.

2023-01-24 01:24 UTC, swati-nair commented on install-operator.html.md.erb
> +1.  Push the VMware MySQL Operator Docker images to the container registry of your choice. Set each image's project and image repo name, tag the images, and then push them using the Docker command `d
Let's avoid Operator here too. It can cause confusion that this line only means the operator image and not instance.

2023-01-24 01:24 UTC, swati-nair commented on install-operator.html.md.erb
> +    <p class='note important'><strong>IMPORTANT:</strong> Re-run the commands below to create identical or equivalent secrets in every namespace in which users will create VMware MySQL Operator insta
same. no `Operator`.

2023-01-24 01:24 UTC, swati-nair commented on install-operator.html.md.erb
> +          <td>The registry from which to download VMware MySQL Operator images.</td>
no `Operator` needed

2023-01-24 01:24 UTC, swati-nair commented on monitoring.html.md.erb
> +title: Monitoring VMware SQL with MySQL Operator Instances in Kubernetes
can avoid long name

2023-01-24 01:24 UTC, swati-nair commented on monitoring.html.md.erb
> +For a list of the exposed VMware MySQL Operator metrics collectors see [MySQL Server Exporter Collector Flag Reference](#collectors).
let's avoid Operator here

2023-01-24 01:24 UTC, swati-nair commented on monitoring.html.md.erb
> +During the VMware MySQL Operator initialization, the VMware MySQL Operator creates a metrics related self-signed certificate. The TLS credentials are stored in a Secret named after the MySQL instance
let's avoid the first Operator

2023-01-24 01:24 UTC, swati-nair commented on network-policies.html.md.erb
> +To successfully deploy the VMware MySQL Operator you need to allow communication between pods, Operator, API server and services. For details see [Allowing Operator Communication](#operator_configura
same here.

2023-01-24 01:24 UTC, swati-nair commented on upgrade-instance.html.md.erb
> +title: Upgrading VMware SQL with MySQL for Kubernetes Instances
I think for all the titles related to instance, you can avoid an update since it doesn't mention Tanzu and to keep it short.

2023-01-24 01:24 UTC, swati-nair commented on variables.yml
> +  product_short: VMware MySQL Operator
Is this consistent with postgres operator?

2023-01-24 01:34 UTC, SMiller70 commented on variables.yml
> +  product_short: VMware MySQL Operator
It is, and for the cases where Operator was used above, but could be dropped, I was leaning towards using the short name of `VMware MySQL Operator` rather than `VMware MySQL` to keep it consistent with the postgres side. Its something I'll bring up when we have our next docs sync

2023-01-24 15:05 UTC, abubakarm94 commented on create-delete-mysql.html.md.erb
> +    NAME           READY   STATUS    AGE    VMWARE VERSION   DB VERSION   UPDATE STATUS       USER ACTION
If there a PR to change this in the code? If not, let's not update it just yet.

2023-01-24 17:25 UTC, swati-nair commented on variables.yml
> +  product_short: VMware MySQL Operator
Ahh, got it. This one makes sense to update `product_short`. For other comments, I particularly added a comment  where it refers to the VMware SQL instances. So, adding an `Operator` in those lines can cause confusion that are we talking about the operator itself or the instance. I see that the postgres docs has kept it as is (for eg: Accessing a Postgres Instance in Kubernetes, Deleting a Postgres Instance, etc.)

2023-02-10 01:10 UTC, dyozie requested changes

2023-02-10 01:10 UTC, dyozie commented on release-notes.html.md.erb
> +- Before installing the Tanzu MySQL operator, this release now requires cert-manager installation. For details, see [Prerequisites for Installing via the Tanzu Network Registry](./install-operator.ht
Missed changing an instance of "Tanzu" in this sentence.

2023-02-10 01:10 UTC, dyozie commented on update-instance.html.md.erb
> +    NAME           READY   STATUS    AGE    VMWARE VERSION   DB VERSION   UPDATE STATUS      USER ACTION
As with previous comment, this will be dependent on a code PR.  Not sure if that's in place.

2023-02-13 23:14 UTC, SMiller70 commented on release-notes.html.md.erb
> +- Before installing the Tanzu MySQL operator, this release now requires cert-manager installation. For details, see [Prerequisites for Installing via the Tanzu Network Registry](./install-operator.ht
For the postgres rebranding, we left the release notes alone for previously released versions. Did we want to match that over here, or update the naming for older versions?

2023-02-21 15:36 UTC, dyozie commented on release-notes.html.md.erb
> +- Before installing the Tanzu MySQL operator, this release now requires cert-manager installation. For details, see [Prerequisites for Installing via the Tanzu Network Registry](./install-operator.ht
Right - it's probably fine to leave the previous version notes as-is.

2023-02-21 15:36 UTC, dyozie approved these changes

2023-02-22 18:14 UTC, merged