Move deployment template download from 'Installing the Operator' to 'Creating and Deleting MySQL Instances'
pivotal-cf/docs-mysql-k8s pull request #61
Opened 2021-07-20 17:07 UTC by fifthposition

Name the branches to merge this change with or enter "None": `main`

In https://www.pivotaltracker.com/story/show/176914690, we decided to move the step of downloading deployment templates, from 'Installing the Operator' to 'Creating and Deleting MySQL Instances'. The reasoning was that the templates are not used when installing the product, but are first used when creating a MySQL instance.

Created a new section, 'Download the Deployment Templates', in 'Creating and Deleting MySQL Instances'. Other topics can link to this section when referring to the templates.

Also made some other small editorial changes, such as lowercasing 'operator' throughout 'Installing the Operator'.

2021-07-20 23:02 UTC, lenapivotal commented on create-delete-mysql.html.md.erb
> +You do not need to download the **Artifact References** from the Tanzu MySQL for Kubernetes product page.
I think we could mention that a TGZ file is downloaded and then list all the available templates that they can find in the ./samples/ folder?

2021-07-21 21:00 UTC, fifthposition commented on create-delete-mysql.html.md.erb
> +You do not need to download the **Artifact References** from the Tanzu MySQL for Kubernetes product page.
We can mention the file type, but I'm not sure that this is the place to list all available samples, since most aren't relevant to this topic.

2021-07-21 21:02 UTC, fifthposition commented on create-delete-mysql.html.md.erb
> +You do not need to download the **Artifact References** from the Tanzu MySQL for Kubernetes product page.
I should mention that when I say "we decided", I don't literally include myself, since I wasn't involved in that discussion (just picking up the story to do this long afterward). :-) I think 'Creating and Deleting' is a better place to put this section than 'Installing the Operator', but I'm not certain how best to cover this info, since it's more general than simply getting templates for MySQL instances only.

2021-07-21 21:37 UTC, lenapivotal commented on create-delete-mysql.html.md.erb
> +You do not need to download the **Artifact References** from the Tanzu MySQL for Kubernetes product page.
We are in the "creating and deleting page"... I always find it useful and comforting to list what is downloaded, even if not all the files are used in this page. So the user knows he's got the right stuff.

2021-07-21 22:27 UTC, fifthposition commented on create-delete-mysql.html.md.erb
> +You do not need to download the **Artifact References** from the Tanzu MySQL for Kubernetes product page.
Sorry... I just meant, I do agree that this page is a better fit for the info than where it originally was ("Installing the Operator"), but I wasn't around when this decision was made, so I don't have much context.

I've added info about the file and I'll add a list of all the templates.

2021-07-22 17:28 UTC, ssapra requested changes
Just one note on the name of the release artifact on TanzuNet

2021-07-22 17:28 UTC, ssapra commented on create-delete-mysql.html.md.erb
> +1. Click **Tanzu MySQL Deployment Templates**. The deployment templates will be downloaded as a .tgz archive file to your local machine.
As of 1.1.0, we don't actually provide a tarball archive that is _only_ the deployment templates. We are providing a tarball like `VMware Tanzu SQL with MySQL for Kubernetes v1.1.0`. After expanding that file, there will be a `samples` directory, so all of the details below remain the same.

2021-07-22 19:55 UTC, lenapivotal commented on create-delete-mysql.html.md.erb
> +1. Click **Tanzu MySQL Deployment Templates**. The deployment templates will be downloaded as a .tgz archive file to your local machine.
@ssapra when the user expands the file, he sees the samples directory but what's the parent directory called? In Postgres we call it "postgres-for-kubernetes-v1.2.0"

@fifthposition we need to edit all the locations that say "Find the `backuplocation.yaml` deployment template that you downloaded in the **Tanzu MySQL Deployment Templates** TGZ file from <%= vars.product_network %>."

2021-07-22 19:58 UTC, ssapra commented on create-delete-mysql.html.md.erb
> +1. Click **Tanzu MySQL Deployment Templates**. The deployment templates will be downloaded as a .tgz archive file to your local machine.
@lenapivotal The directory would be `tanzu-mysql-for-kubernetes-1.1.0`

2021-08-10 20:52 UTC, fifthposition commented on create-delete-mysql.html.md.erb
> +1. Click **Tanzu MySQL Deployment Templates**. The deployment templates will be downloaded as a .tgz archive file to your local machine.
Updated. @lenapivotal I removed references to the _name_ of the file, so it just refers to "the TGZ file from..."--to mem, that seems simpler to maintain.

2021-08-16 17:04 UTC, merged