“Installing the Operator": add section about install based on downloaded archive
pivotal-cf/docs-mysql-k8s pull request #66
Opened 2021-08-17 22:16 UTC by fifthposition

2021-08-17 22:58 UTC, lenapivotal requested changes
some small things to edit... if you agree.

2021-08-17 22:58 UTC, lenapivotal commented on install-operator.html.md.erb
> +## <a id="access"></a> Access the Resources
This header maybe you meant it to be ### ?

2021-08-17 22:58 UTC, lenapivotal commented on install-operator.html.md.erb
>  ### <a id="create-namespace-secret"></a> Create Namespace and Secret
Does this need to be #### ? It feels you're creating a "Install Operator" section on the right hand side, with no content and the "Create Namespace and Secret" are same level. So overall it results in 6 steps instead of 4 ....

2021-08-17 22:58 UTC, lenapivotal commented on install-operator.html.md.erb
> +
something is off here....

2021-08-20 21:50 UTC, kimago commented on install-operator.html.md.erb
> +- Or you wish to load the Operator and instance images to private Docker registry.
to a private Docker Regisitry.

2021-08-20 21:53 UTC, kimago commented on install-operator.html.md.erb
> +- Or you wish to load the Operator and instance images to private Docker registry.
Make "private Docker registry" "**a** private Docker registry":
Or you wish to load the Operator and instance images to a private Docker registry.

2021-08-20 21:55 UTC, kimago commented on install-operator.html.md.erb
> +Before you deploy the <%=vars.product_full %> Operator, review the list of [Prerequisites](#prereq) that apply to both installation methods.
Anchor on Prerequisites page seems to have changed to #tanzu-prereq ?

2021-08-20 22:26 UTC, dsharp-pivotal commented on install-operator.html.md.erb
> +Create a `docker-registry` type secret to allow the Kubernetes cluster to authenticate with the private container registry so it can pull images. These examples create a secret named `regsecret` usin
s/regsecret/tanzu-image-registry

2021-08-20 22:26 UTC, dsharp-pivotal commented on install-operator.html.md.erb
> +3. If you want to deploy the Tanzu MySQL images from a registry
Drop this bullet

2021-08-20 22:26 UTC, dsharp-pivotal commented on install-operator.html.md.erb
>  Status: Downloaded newer image for registry.pivotal.io/tanzu-mysql-for-kubernetes/tanzu-mysql-operator:1.1.0
Drop these two `docker pull` instructions

2021-08-20 22:29 UTC, dsharp-pivotal commented on install-operator.html.md.erb
> +    pod/mysql-operator-69765b8b74-rtms7            1/1         Running          0             3d19h
s/mysql-operator/tanzu-mysql-operator

2021-09-01 22:19 UTC, fifthposition commented on install-operator.html.md.erb
> +Before you deploy the <%=vars.product_full %> Operator, review the list of [Prerequisites](#prereq) that apply to both installation methods.
There's two 'Prerequisites' -- one for each install method. I've renamed them:

* `tanzu-network-prerequisites`
* `download-archive-prerequisites`

2021-09-03 21:51 UTC, fifthposition commented
Updated based on feedback. Page is at https://mysql-k8s-install-archive.sc2-04-pcf1-apps.oc.vmware.com/tanzu-mysql-kubernetes/1-1/install-operator.html

2021-09-07 20:49 UTC, lenapivotal commented on install-operator.html.md.erb
> +Before you deploy the <%=vars.product_full %> Operator, review the list of [Prerequisites](#prereq) that apply to both installation methods.
Ben,this is a page that is frequently referred to from other pages. Please can you check and edit the locations where we refer to "prereq" tag? There's at least 3 pages.

2021-09-07 20:50 UTC, lenapivotal commented on install-operator.html.md.erb
> +To install the Tanzu MySQL operator, you must download the Helm chart and images.
Please could you check if the older tag was used anywhere else in the repo? And replace?

2021-09-07 20:54 UTC, lenapivotal commented on install-operator.html.md.erb
> +
Same about this id tag that was changed. Thank you

2021-09-07 20:56 UTC, lenapivotal commented
@fifthposition we have added a note about network policies in this page now. There will be merge conflicts.

2021-09-07 23:08 UTC, dsharp-pivotal reviewed
Broad strokes look good. Some of the details are inaccurate or inconsistent, though. See comments.

2021-09-07 23:08 UTC, dsharp-pivotal commented on install-operator.html.md.erb
> +    Helm installs the new release into the Kubernetes namespace specified in the current Kubernetes context. The command displays a message similar to:
Since the `helm` command above includes `--namespace=${OPERATOR_NAMESPACE}`, it will get installed in that namespace. I think these instructions should be consistent with the others, and recommend installing in `mysql-for-kubernetes-system`. (This was probably inherited from Postgres's instructions.)

2021-09-08 21:56 UTC, fifthposition commented on install-operator.html.md.erb
> +Before you deploy the <%=vars.product_full %> Operator, review the list of [Prerequisites](#prereq) that apply to both installation methods.
For now, I made those pages link only to the topic, not to the 'Prerequisites' section, because there are now _two_ 'Prerequisites' sections. Also, I wonder if we really need to be including cert-manager installation instructions in our documentation--can we not simply link back to the CM site for that?

2021-09-08 21:56 UTC, fifthposition commented on install-operator.html.md.erb
> +To install the Tanzu MySQL operator, you must download the Helm chart and images.
You mean replace all other occurrences of `product_short`? I can do that, but not sure it belongs in this PR.

2021-09-08 21:59 UTC, fifthposition commented on install-operator.html.md.erb
> +To install the Tanzu MySQL operator, you must download the Helm chart and images.
I've checked and see no references to it.

2021-09-08 22:02 UTC, fifthposition commented on install-operator.html.md.erb
> +
I don't see what the previous id was. I don't see any other pages linking to `#install-operator` (which I did remove).

2021-09-08 22:04 UTC, fifthposition commented on install-operator.html.md.erb
> +- A running Kubernetes cluster - [Google Kubernetes Engine (GKE)](prepare-gke.html), [VMware Enterprise TKGi)](prepare-pks.html) or [Minikube](minikube.html) - and the [kubectl](https://kubernetes.io
No--this is left over from when I copied the content from Postgres 🤦. Removing

2021-09-08 22:07 UTC, fifthposition commented on install-operator.html.md.erb
> +      --create-namespace \
Added `--values`

2021-09-08 22:08 UTC, fifthposition commented on install-operator.html.md.erb
> +**IMPORTANT**: The commands below create the secret in the `default` namespace. Only pods created in the same `default` namespace can reference the secret. To create a secret in a different namespace
cc @lenapivotal (this content was copied from Postgres)

2021-09-08 22:24 UTC, lenapivotal commented on install-operator.html.md.erb
> +**IMPORTANT**: The commands below create the secret in the `default` namespace. Only pods created in the same `default` namespace can reference the secret. To create a secret in a different namespace
@fifthposition this warning is valid for Postgres docs, because we didn't specify NAMESPACE during instance creation. If mySQL does, then it doesn't need to be so obvious.

2021-09-08 22:28 UTC, lenapivotal commented on install-operator.html.md.erb
> +Before you deploy the <%=vars.product_full %> Operator, review the list of [Prerequisites](#prereq) that apply to both installation methods.
Lets leave cert manager as is for now. We can create a short topic somewhere else and avoid this long section but this is new for mySQL for this release, so it's best to avoid sending them to third party docs.

2021-09-09 02:22 UTC, fifthposition commented on install-operator.html.md.erb
> +Before you deploy the <%=vars.product_full %> Operator, review the list of [Prerequisites](#prereq) that apply to both installation methods.
My bigger concern is that we have two "Prerequisites" sections on the page now and I don't want to refer readers to "_the_ Prerequisites section of 'Installing the Operator'".

I haven't removed the CM instructions, but I had removed the links to "Prerequisites". I guess I can add the links back in.

2021-09-09 02:25 UTC, fifthposition commented on install-operator.html.md.erb
> +**IMPORTANT**: The commands below create the secret in the `default` namespace. Only pods created in the same `default` namespace can reference the secret. To create a secret in a different namespace
Rephrased here.

2021-09-09 02:26 UTC, fifthposition commented on install-operator.html.md.erb
> +    Helm installs the new release into the Kubernetes namespace specified in the current Kubernetes context. The command displays a message similar to:
Changed to `mysql-for-kubernetes-system`.

2021-09-09 02:48 UTC, fifthposition commented on install-operator.html.md.erb
> +Before you deploy the <%=vars.product_full %> Operator, review the list of [Prerequisites](#prereq) that apply to both installation methods.
I've renamed the two "Prerequisites" sections to be specific and other pages now link to the first (the one for installing via Tanzu Network).

2021-09-09 02:52 UTC, fifthposition commented
Revised based on feedback. Updated the page on the staging site: https://mysql-k8s-install-archive.sc2-04-pcf1-apps.oc.vmware.com/tanzu-mysql-kubernetes/1-1/install-operator.html

@lenapivotal There was a merge conflict when I came back to this today, but I resolved it.

2021-09-09 17:54 UTC, dsharp-pivotal reviewed
LGTM otherwise.

2021-09-09 17:54 UTC, dsharp-pivotal commented on install-operator.html.md.erb
> +    where `-n mysql-operator` defines the namespace. The output would be similar to:
Probably want to switch these to `mysql-for-kubernetes-system` as well.

2021-09-09 22:20 UTC, dsharp-pivotal approved these changes

2021-09-15 18:10 UTC, dyozie approved these changes

2021-09-15 18:11 UTC, merged